version: '3.7'
# ====================================== AIRFLOW ENVIRONMENT VARIABLES =======================================
x-environment: &airflow_environment
  - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres:5432/airflow
  - AIRFLOW__CORE__STORE_DAG_CODE=True
  - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  - AIRFLOW__WEBSERVER__RBAC=False
  - CHROME_BIN=/usr/bin/google-chrome-stable
  - DISPLAY=:99   
  - CHROME_DRIVER_PATH=/root/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver
x-airflow-image: &airflow_image extending_airflow:latest
# ====================================== /AIRFLOW ENVIRONMENT VARIABLES ======================================
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432"
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_INSTANCES=1
      - SE_NODE_MAX_SESSION=1

  init:
    image: *airflow_image
    depends_on:
      - postgres
    environment: *airflow_environment
    entrypoint: /bin/bash
    command: -c 'airflow db upgrade && sleep 5 && airflow db init && airflow users create --username airflow --password airflow --firstname air --lastname flow --role Admin --email airflow@gmail.com'
  webserver:
    image: *airflow_image
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - logs:/opt/airflow/logs
      - ./dags/src/screenshots:/opt/airflow/dags/src/screenshots
      - ./dags/src/output:/opt/airflow/dags/src/output

    environment: *airflow_environment
    command: webserver
  scheduler:
    image: *airflow_image
    restart: always
    user: root
    depends_on:
      - postgres
      - webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./configurations.json:/tmp/conf_file/configurations.json
      - logs:/opt/airflow/logs
      - ./dags/src/screenshots:/opt/airflow/dags/src/screenshots
      - ./dags/src/output:/opt/airflow/dags/src/output
      - /opt/airflow/.cache/ms-playwright:/opt/airflow/.cache/ms-playwright
    environment: *airflow_environment
    command: scheduler
volumes:
  logs:
